version: '3.1'
services:
  db:
    image: mysql
    container_name: championshipApp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - championshipApp:/var/lib/mysql

volumes:
  championshipApp: