version: '3.1'
services:
  db:
    image: postgres
    container_name: championshipApp
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: championshipApp
    ports:
      - "3308:5432"
    volumes:
      - championshipApp:/var/lib/postgres

volumes:
  championshipApp: